// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PADocGenerator.Api.Data;

#nullable disable

namespace PADocGenerator.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260820100000_AddPowerPlatformFlowImport")]
partial class AddPowerPlatformFlowImport
{
}
